[package]
name = "api-types"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21"
regex = "1.12"
serde = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
utils = { workspace = true }
