[package]
name = "api-types"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21"
regex = "1.12"
serde = { version = "1.0", features = ["derive"] }
time = { version = "0.3.45", features = ["serde"] }
tracing = "0.1"
