[package]
name = "middleware"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
axum-extra = { version = "0.12.5", features = ["cookie"] }
tracing = { workspace = true }
utils = { workspace = true }
